Build/local dev
bcgov/nr-spar-oracle-api pull request #59
Opened 2023-01-16 18:33 UTC by annibalsilva

# Description

Try to ease local development with Docker. Changes include:

1. Disable Keycloak via the `KEYCLOAK_ENABLED` environment variable when its value is `false`
2. Allow setting JVM options via the `JAVA_OPTS` environment variable when running the application with Docker
3. Create scripts to build and run the application's Docker image without the need to rebuild it every time the application code changes
4. Allow the optional use of a file with environment variables to be used in the scripts

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2023-01-19 21:04 UTC, RMCampos requested changes
Works great!! Good job. Just a small fix to keep it working with docker-compose.

2023-01-25 17:19 UTC, annibalsilva commented on dockerfile-entrypoint.sh
> +    /usr/share/service/target/backend-start-api.jar
I made some changes that work without volumes now.

2023-01-25 18:34 UTC, DerekRoberts approved these changes
Looks good!  :)

2023-01-25 21:04 UTC, annibalsilva commented
> ...a few required jobs haven't completed. That's outside the scope of this PR, right?

Yes, this one is just to make local development with Docker easier.

2023-01-31 18:23 UTC, RMCampos requested changes

2023-01-31 18:28 UTC, annibalsilva commented on docker-compose.yml
> +    dns: ${DNS}
Is it a good idea to publish the VPN's DNS address in the repository?

2023-01-31 18:31 UTC, RMCampos commented on docker-compose.yml
> +    dns: ${DNS}
Maybe we could give the command to populate this variable. nslookup.

2023-02-06 17:24 UTC, RMCampos approved these changes
LGTM

2023-02-06 17:48 UTC, merged