feat: endpoints for seedlot status
bcgov/nr-spar-oracle-api pull request #79
Opened 2023-02-14 22:13 UTC by annibalsilva

# Description

Create endpoints to fetch seed lot status, which will be all represented in the system by enums for now.

Fixes [FSADT2-491](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-491)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- Manually
- Unit tests

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2023-02-14 22:30 UTC, annibalsilva commented
@mgaseta, can you check the [endpoints documentation](https://nr-spar-oracle-api-79-service-api.apps.silver.devops.gov.bc.ca/swagger-ui/index.html#/seedlot)? I'd also like your opinion on whatever fetching by code will be useful or not (see the [Jira task](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-491) for a short summary).

2023-02-15 11:06 UTC, RMCampos approved these changes
Great work! Small changes and we're good to go!

2023-02-15 11:06 UTC, RMCampos commented on src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotStatusEndpoint.java
> +@Tag(name = "seedlot")
I think the tag should point to the endpoint, in this case `SeedlotStatus`.

2023-02-15 11:06 UTC, RMCampos commented on src/main/java/ca/bc/gov/backendstartapi/config/SwaggerConfig.java
> +                    "/api/seedlot-status",
Paths are discovered automatically by spring-doc. Don't need to register them in the code.

2023-02-15 11:14 UTC, RMCampos requested changes
Oops. Clicked the wrong button. Once those changes are addressed it's all good.

2023-02-15 12:20 UTC, RMCampos commented
I was thinking here. Is that necessairy to "generify" them? Because we still are going to need an especific class for each enumeration. Also one class for each one. So I think we could go with the traditional style. Create a simple enum class containing code a description, and an endpoint class to hold the GET method and the path.

2023-02-15 17:00 UTC, mgaseta approved these changes
@annibalsilva The documentation looks great, and regarding the code fetch, it doesn't seem necessary at the moment, we also have an enum on the client that can map status, so it may be redundant to have this endpoint also. But it may have functionality for the project in the future that I can't imagine right now, so I don't think it should be removed yet.

2023-02-15 18:50 UTC, annibalsilva commented
Reopened in [PR 53 of bcgov/nr-spar-backend](https://github.com/bcgov/nr-spar-backend/pull/53).

2023-02-15 18:50 UTC, closed without merging